"""empty message

Revision ID: 525e7abc6b55
Revises: de06a7801c35
Create Date: 2024-12-07 00:29:24.013309

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '525e7abc6b55'
down_revision = 'de06a7801c35'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('anda_user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(length=250), nullable=True))

    with op.batch_alter_table('location', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(length=250), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('location', schema=None) as batch_op:
        batch_op.drop_column('image_url')

    with op.batch_alter_table('anda_user', schema=None) as batch_op:
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###
