"""empty message

Revision ID: c8453b57a966
Revises: 
Create Date: 2024-12-09 22:52:06.495279

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8453b57a966'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('anda_user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('image_url', sa.String(length=250), nullable=True))

    with op.batch_alter_table('location', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(length=250), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('location', schema=None) as batch_op:
        batch_op.drop_column('image_url')

    with op.batch_alter_table('anda_user', schema=None) as batch_op:
        batch_op.drop_column('image_url')
        batch_op.drop_column('password')

    # ### end Alembic commands ###
